language: node_js

before_install:
  - sudo apt-get install -y pandoc

node_js:
  - node

install:
  - npm install

script:
  - npm test      # validate examples against JSON Schema
  - make          # build jskos.html

after_success:
  - cp jskos.html gh-pages
  - cp context.json gh-pages
  - cp schemas/*.json gh-pages

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  local-dir: gh-pages
  on:
    branch: master
    tags: true
